name: 'TypeScript builds'
on:
  pull_request:
      types: [opened, edited, synchronize, reopened]
      paths:
        - 'src/typescript/**'
        - '.github/workflows/typescript.yml'
  workflow_dispatch:

jobs:
  Application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Build 01 Http Function'
        shell: bash
        run: |
          pushd './src/typescript/AzureFunctions.Http/01CreatingAFunctionApp'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build 02 Http Function'
        shell: bash
        run: |
          pushd './src/typescript/AzureFunctions.Http/02ChangingTheTemplateForGetRequest'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build 03 Http Function'
        shell: bash
        run: |
          pushd './src/typescript/AzureFunctions.Http/03ChangingTheTemplateForPostRequests'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build 04 Http Function'
        shell: bash
        run: |
          pushd './src/typescript/AzureFunctions.Http/04AddingANewFunctionForPostRequests'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build Blob Function'
        shell: bash
        run: |
          pushd './src/typescript/AzureFunctions.Blob'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build DurableFunctionApp'
        shell: bash
        run: |
          pushd './src/typescript/durable-functions/chaining/DurableFunctionApp'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build DurableFunctionApp-Retry'
        shell: bash
        run: |
          pushd './src/typescript/durable-functions/chaining/DurableFunctionApp-Retry'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build DurableFunctionApp-Timeout'
        shell: bash
        run: |
          pushd './src/typescript/durable-functions/chaining/DurableFunctionApp-Timeout'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build DurableFunctionApp-AdvancedPatterns-FanOutFanIn'
        shell: bash
        run: |
          pushd './src/typescript/durable-functions/advanced-patterns/01DurableFunctionApp-FanOutFanIn'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build DurableFunctionApp-AdvancedPatternsSubOrchestration'
        shell: bash
        run: |
          pushd './src/typescript/durable-functions/advanced-patterns/02DurableFunctionApp-SubOrchestration'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build DurableFunctionApp-AdvancedPatternsExternalEvent'
        shell: bash
        run: |
          pushd './src/typescript/durable-functions/advanced-patterns/03DurableFunctionApp-ExternalEvent'
          npm ci
          npm run build --if-present
          popd
