name: 'TypeScript builds'
on:
  pull_request:
      types: [opened, edited, synchronize, reopened]
      paths:
        - 'src/typescript/**'
        - '.github/workflows/typescript.yml'
  workflow_dispatch:

jobs:
  Application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Build Http Function'
        shell: bash
        run: |
          pushd './src/typescript/AzureFunctions.Http/01CreatingAFunctionApp'
          npm ci
          npm run build --if-present
          popd
      - name: 'Build Blob Function'
        shell: bash
        run: |
          pushd './src/typescript/AzureFunctions.Blob'
          npm ci
          npm run build --if-present
          popd
